### ISSUE TITLE
[FR] option to move tool head between CARTOGRAPHER_TOUCH retries

### ISSUE THREAD

**Issue by TomW1605** [Cartographer3D/cartographer-klipper#34] opened 2024-09-03 07:42 UTC
i find that more often than not my touch process will fail the first go through (10 retries) and then once i clean all the plastic that oozed out while it was running off the nozzle and bed it will work within the first few retries the next go. it would be great to have an option to have it move the tool ~5mm between each retry so that it is not tapping over the same bit of plastic on the bed the whole time messing up the results

**Comment by krautech** [comment] 2024-09-16 04:46
Duplicate of [Issue #35](https://github.com/Cartographer3D/cartographer-klipper/issues/35)

**Closed by krautech** 2024-09-16 04:46 UTC
Labels: duplicate
